### ISSUE TITLE
install theme

### ISSUE THREAD

**Issue by brettfarley** [brettfarley/martinez#1]
Here's the theme file for electryanmartinez.com in GoDaddy. Please install the 'full screen slider' version of the theme as laid out here: http://demo.themealien.com/onehost/

https://www.dropbox.com/s/50bo92bbru64mek/Onehost-Package.zip?dl=0

**Comment by arish-ricom** [comment]
Dear Brett,

The theme have been installed and deployed to FE godaddy hosting. Please add the following line into your hosts file which you have done last time for amconpac.com

72.167.232.195  www.electryanmartinez.com

So that you'll edit it from your system and once it is ready, it will be made public.

Thanks & Regards
Arish

**Comment by arish-ricom** [comment]
Find the wp login in the wiki : https://github.com/VeritasStrategies/martinez/wiki
